--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activityjournal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activityjournal (
    recordid integer NOT NULL,
    studentid integer,
    subjectid integer,
    themeid integer,
    classid integer,
    theme1 character varying(255),
    theme2 character varying(255),
    theme3 character varying(255),
    theme4 character varying(255),
    activity1 character varying(255),
    activity2 character varying(255),
    activity3 character varying(255),
    activity4 character varying(255)
);


ALTER TABLE public.activityjournal OWNER TO postgres;

--
-- Name: activityjournal_recordid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.activityjournal ALTER COLUMN recordid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activityjournal_recordid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: class; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.class (
    classid integer NOT NULL,
    classname character varying(255) NOT NULL
);


ALTER TABLE public.class OWNER TO postgres;

--
-- Name: class_classid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.class ALTER COLUMN classid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_classid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: classsubject; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.classsubject (
    classid integer NOT NULL,
    subjectid integer NOT NULL
);


ALTER TABLE public.classsubject OWNER TO postgres;

--
-- Name: offset; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."offset" (
    offsetid integer NOT NULL,
    offsetname character varying(255) NOT NULL,
    subjectid integer,
    distance character varying(255) NOT NULL
);


ALTER TABLE public."offset" OWNER TO postgres;

--
-- Name: offset_offsetid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."offset" ALTER COLUMN offsetid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.offset_offsetid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: presence; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.presence (
    recordid integer NOT NULL,
    ispresence character varying(255),
    classid integer,
    studentid integer,
    subjectid integer,
    themeid integer
);


ALTER TABLE public.presence OWNER TO postgres;

--
-- Name: presence_recordid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.presence ALTER COLUMN recordid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.presence_recordid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: runjournal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.runjournal (
    recordid integer NOT NULL,
    studentid integer,
    subjectid integer,
    offsetid integer,
    classid integer,
    estimation character varying(255),
    "time" character varying(255)
);


ALTER TABLE public.runjournal OWNER TO postgres;

--
-- Name: runjournal_recordid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.runjournal ALTER COLUMN recordid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.runjournal_recordid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student (
    studentid integer NOT NULL,
    fullname character varying(255) NOT NULL,
    dateofbirth character varying(255) NOT NULL,
    classid integer
);


ALTER TABLE public.student OWNER TO postgres;

--
-- Name: student_studentid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student ALTER COLUMN studentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_studentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subject; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subject (
    subjectid integer NOT NULL,
    subjectname character varying(255) NOT NULL
);


ALTER TABLE public.subject OWNER TO postgres;

--
-- Name: subject_subjectid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subject ALTER COLUMN subjectid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subject_subjectid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: theme; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.theme (
    themeid integer NOT NULL,
    themename character varying(255) NOT NULL,
    subjectid integer,
    themedate character varying(255)
);


ALTER TABLE public.theme OWNER TO postgres;

--
-- Name: theme_themeid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.theme ALTER COLUMN themeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.theme_themeid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: themejournal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.themejournal (
    recordid integer NOT NULL,
    studentid integer,
    subjectid integer,
    themeid integer,
    classid integer,
    estimation1 character varying(255),
    estimation2 character varying(255),
    estimation3 character varying(255),
    estimation4 character varying(255),
    coment1 character varying(255),
    coment2 character varying(255),
    coment3 character varying(255),
    coment4 character varying(255),
    lessondate character varying(255)
);


ALTER TABLE public.themejournal OWNER TO postgres;

--
-- Name: themejournal_recordid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.themejournal ALTER COLUMN recordid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.themejournal_recordid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: theory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.theory (
    theoryid integer NOT NULL,
    theorytext text,
    themeid integer
);


ALTER TABLE public.theory OWNER TO postgres;

--
-- Name: theory_theoryid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.theory ALTER COLUMN theoryid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.theory_theoryid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    login character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    userid integer NOT NULL
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- Name: user_userid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN userid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_userid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: activityjournal; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.activityjournal (recordid, studentid, subjectid, themeid, classid, theme1, theme2, theme3, theme4, activity1, activity2, activity3, activity4) FROM stdin;
\.


--
-- Data for Name: class; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.class (classid, classname) FROM stdin;
\.


--
-- Data for Name: classsubject; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.classsubject (classid, subjectid) FROM stdin;
\.


--
-- Data for Name: offset; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."offset" (offsetid, offsetname, subjectid, distance) FROM stdin;
\.


--
-- Data for Name: presence; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.presence (recordid, ispresence, classid, studentid, subjectid, themeid) FROM stdin;
\.


--
-- Data for Name: runjournal; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.runjournal (recordid, studentid, subjectid, offsetid, classid, estimation, "time") FROM stdin;
\.


--
-- Data for Name: student; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student (studentid, fullname, dateofbirth, classid) FROM stdin;
\.


--
-- Data for Name: subject; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subject (subjectid, subjectname) FROM stdin;
\.


--
-- Data for Name: theme; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.theme (themeid, themename, subjectid, themedate) FROM stdin;
\.


--
-- Data for Name: themejournal; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.themejournal (recordid, studentid, subjectid, themeid, classid, estimation1, estimation2, estimation3, estimation4, coment1, coment2, coment3, coment4, lessondate) FROM stdin;
\.


--
-- Data for Name: theory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.theory (theoryid, theorytext, themeid) FROM stdin;
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."user" (login, password, userid) FROM stdin;
\.


--
-- Name: activityjournal_recordid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activityjournal_recordid_seq', 1, false);


--
-- Name: class_classid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.class_classid_seq', 1, false);


--
-- Name: offset_offsetid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.offset_offsetid_seq', 1, false);


--
-- Name: presence_recordid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.presence_recordid_seq', 1, false);


--
-- Name: runjournal_recordid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.runjournal_recordid_seq', 1, false);


--
-- Name: student_studentid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_studentid_seq', 1, false);


--
-- Name: subject_subjectid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subject_subjectid_seq', 1, false);


--
-- Name: theme_themeid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.theme_themeid_seq', 1, false);


--
-- Name: themejournal_recordid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.themejournal_recordid_seq', 1, false);


--
-- Name: theory_theoryid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.theory_theoryid_seq', 1, false);


--
-- Name: user_userid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_userid_seq', 1, false);


--
-- PostgreSQL database dump complete
--

